export const ROUTES = {
  LOGIN: "LOGIN",
  REGISTER: "REGISTER",
  FORGOT_PASSWORD: "FORGOT_PASSWORD",
  HOME_TABS: "HOME_TABS",
  HOME: "HOME",
  FEED: "FEED",
  MY_TIPSTERS: "MY_TIPSTERS",
  MY_TIPSTERS_FEED: "MY_TIPSTERS_FEED",
  HISTORY: "HISTORY",
  MY_RESULTS: "MY_RESULTS",
  MY_SOCIAL_NETWORK_HOME: "MY_SOCIAL_NETWORK_HOME",
};
